args:
  name: deepseek-v3.1-671b
  gpu_type: nvidia-h200-141gb
  tp: 8
  metadata:
    description: DeepSeek V3.1 671B
    provider: DeepSeek
    gpu_recommendation: Nvidia GPUs with at least 141GBx8 VRAM (e.g. about 8 H200 GPUs).
  model_id: deepseek-ai/DeepSeek-V3.1
  tool_parser: deepseek_v3
  cli_args:
    - '--chat-template'
    - 'templates/tool_deepseek_v3.jinja'
    - '--trust-remote-code'
  envs:
    - name: HF_TOKEN
  attn_backend: 'FLASHMLA'
  hf_generation_config:
    temperature: 0.3
    top_p: 0.9
