args:
  name: gpt-oss-20b
  gpu_type: nvidia-h100-80gb
  tp: 1
  metadata:
    description: GPT OSS MoE 20B
    provider: OpenAI
    gpu_recommendation: Nvidia GPUs with at least 80GB VRAM (e.g about 1 H100 GPU).
  model_id: openai/gpt-oss-20b
  autotune: [1,2,4,8,16,24]
  post:
    - uv pip uninstall vllm
    - uv pip install -U openai lmcache nixl
    - uv pip install --pre vllm --extra-index-url https://wheels.vllm.ai/nightly/ --extra-index-url https://download.pytorch.org/whl/nightly/cu128 --index-strategy unsafe-best-match
  exclude:
    - "original/**/*"
    - "metal/**/*"
  attn_backend: TRITON_ATTN_VLLM_V1
  skip_flashinfer: true
  nightly: true
  reasoning_parser: openai_gptoss
  tool_parser: openai
  cli_args:
    - '--chat-template'
    - 'templates/tool_gpt_oss.jinja'
  envs:
    - name: HF_TOKEN
