args:
  name: gpt-oss-120b
  gpu_type: nvidia-h100-80gb
  tp: 2
  metadata:
    description: GPT OSS MoE 120B
    provider: OpenAI
    gpu_recommendation: Nvidia GPUs with at least 140GB VRAM (e.g about 1 H200 GPU or 2xH100 GPUs).
  model_id: openai/gpt-oss-120b
  autotune: [1,2,4,8,16,24]
  post:
    - uv pip install -U openai
    - uv pip install --pre vllm==0.10.1+gptoss --extra-index-url https://wheels.vllm.ai/gpt-oss/ --extra-index-url https://download.pytorch.org/whl/nightly/cu128 --index-strategy unsafe-best-match
  exclude:
    - "original/**/*"
    - "metal"
  attn_backend: FLASH_ATTN
  cli_args:
    - '--chat-template'
    - 'templates/tool_gpt_oss.jinja'
  envs:
    - name: HF_TOKEN
