args:
  name: phi4-14b
  gpu_type: nvidia-h100-80gb
  tp: 1
  model_id: microsoft/phi-4
  autotune: [1,2,4,8,16]
  metadata:
    description: Phi 4 14B
    provider: Microsoft
    gpu_recommendation: an Nvidia GPU with at least 80GB VRAM (e.g about 1 H100 GPU).
  hf_generation_config:
    temperature: 0.8
    top_k: 50
    top_p: 0.95
