args:
  name: qwen3-coder-480b-a35b
  gpu_type: nvidia-h200-141gb
  tp: 4
  metadata:
    description: Qwen 3 Coder 480B A35B MoE
    provider: Alibaba
    gpu_recommendation: Nvidia GPUs with at least 80GBx4 VRAM (e.g about 4 H100 GPUs).
  model_id: Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
  reasoning_parser: qwen3
  autotune: [1,2,4,8,16,24]
  tool_parser: hermes
  max_model_len: 32768
  hf_generation_config:
    temperature: 0.7
    top_k: 20
    top_p: 0.8
    repetition_penalty: 1.05
