args:
  name: qwen3-235b-a22b
  gpu_type: nvidia-h100-80gb
  tp: 4
  metadata:
    description: Qwen 3 235B A22B MoE
    provider: Alibaba
    gpu_recommendation: Nvidia GPUs with at least 80GBx4 VRAM (e.g about 4 H100 GPUs).
  model_id: Qwen/Qwen3-235B-A22B-Instruct-2507-FP8
  reasoning_parser: qwen3
  tool_parser: hermes
  hf_generation_config:
    temperature: 0.7
    top_k: 20
    top_p: 0.8
    min_p: 0
    presence_penalty: 1.5
