args:
  name: qwen3-30b-a3b
  gpu_type: nvidia-h100-80gb
  tp: 2
  metadata:
    description: Qwen 3 30B A3B MoE
    provider: Alibaba
    gpu_recommendation: Nvidia GPU with at least 80GBx2 VRAM (e.g about 2 H100 GPUs or 1 H200 GPU).
  model_id: Qwen/Qwen3-30B-A3B
  autotune: [1,2,4,8,16,24,32,40]
  reasoning_parser: deepseek_r1
  tool_parser: hermes
  hf_generation_config:
    temperature: 0.6
    top_k: 20
    top_p: 0.95
    presence_penalty: 1.5
